services:
  - type: web
    name: kuaforz-randevu
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: "5000"
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: kuafor-randevu-b544e
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: JWT_SECRET
        sync: false
